### ISSUE TITLE
Foundations API - Appointment Timeouts

### ISSUE THREAD

**Issue by BYM-Henry** [reapit/foundations#10315]
Hi Reapit Foundations Team,

**Describe the bug**
We are receiving a large amount of time outs (504) for the appointments collection endpoint (/appointments) for agent (YOM). We currently make 4 requests with an exponential backoff for failed requests, even with this 5,242 / 26,799 appointment endpoint calls timed out 4 times.

We are also getting time outs for the areas collection endpoint (/areas).

We are also seeing occasional timeouts on the following endpoints:

/applicants
/contacts
/landlords
/propertyimages

We are also experienced some failures due to incorrect 429 errors, but this issue has been raised on a separate ticket: #10259 

When doing a full pull our appointment endpoint includes the following parameters (excluding `pageNumber`)

pageSize=100
fromArchive=true & fromArchive=false
includeCancelled=true
includeUnconfirmed=true

This includes the changes we made as part of ticket #10149 to remove filters and sorts from full pulls.

**To Reproduce**
1. Make a appointment collection request for YOM with the above parameters, some pages will timeout.

**Expected behaviour**
The endpoint not to timeout.

**Screenshots**
<img width="1246" alt="image" src="https://github.com/reapit/foundations/assets/51915903/aa56ca23-0e83-4272-9543-176fd3146b47">

**Device (please complete the following information for web issues):**
N/A

**Additional context**
It's been mentioned in the past that it may be possible to add additional indexes to certain databases to stop these timeouts happening, is this something that's possible in this case?

Happy to answer any questions.

Many Thanks,

Henry Fitch
BriefYourMarket

**Comment by plittlewood-rpt** [comment]
Triage notes:

- Initial paging query is taking around 5s because of a workaround for appointments with no date which is causing an index to get ignored on the database
- YOM build has about 900k entries which should be moved to the archive which will give a much better spread of data

**Comment by plittlewood-rpt** [comment]
Internal ticket RSD-264061 logged to arrange diary housekeeping

**Comment by plittlewood-rpt** [comment]
Hi @BYM-Henry 

I've had an initial look at this and ultimately the issues stem from the volume of data being queried. I've reached out to our service desk to look at running some maintenance on the data as there's a huge amount which should actually be moved to the archive which will give a better spread of data as you'll see from my note above.

I've looked at the indexing strategy on the database and the execution plan of the queries being run and have run some tests appropriate to what you are trying to do and can make the following recommendation which hopefully compliments the result of our previous discussion around this subject:

You will likely find the APIs respond much fast if you apply sensible date boundaries to your operations when running the initial pull. As an example, you might choose to pull the data in 6 month blocks which gives the underlying database a much better chance of optimizing the query better as it will be able to use more indexes to filter the data internally

You strategy could be:

1. Set Year (eg 2000)
2. Set Query data boundaries (either 1st Jan - 30th Jun or 1st Jul to 31st Dec)
3. Fetch appointments created in the boundaries set for that year (eg `GET https://platform.reapit.cloud/appointments/?fromArchive=False&includeCancelled=true&includeUnconfirmed=true&createdFrom=2000-01-01T00:00:00Z&createdTo=2000-07-01T00:00:00Z`)
4. Page through the results. Repeat step 2-4 for the second half of the year
5. Repeat entire process incrementing the year until you've read everything up to and including the current data

Again I appreciate this will be a refactor but you'll definitely get better performance. I've run some quick tests on the YOM database. You'll get better performance still if you fetch data a month at time, and so on. 

Can you let me know your thoughts on the above, and how realistic implementing something like this will be?

Thanks

**Comment by plittlewood-rpt** [comment]
Internal ticket logged to try and trace how people are managing to add appointments with null datetime: ACT-748 - if this can be resolved we can remove one of the filters from the appointments API which will reduce the risk of these timeouts occurring as the MySQL optimizer will be able to better optimize the underlying queries

**Comment by BYMIntegrations** [comment]
Hello All,

Please can we CC in Mick.Roscoe@lslps.co.uk in all future correspondences?

This comes from the customer although I understand this may not be possible.

Thanks,

Toby

**Comment by BYM-Henry** [comment]
> Hi @BYM-Henry
> 
> I've had an initial look at this and ultimately the issues stem from the volume of data being queried. I've reached out to our service desk to look at running some maintenance on the data as there's a huge amount which should actually be moved to the archive which will give a better spread of data as you'll see from my note above.
> 
> I've looked at the indexing strategy on the database and the execution plan of the queries being run and have run some tests appropriate to what you are trying to do and can make the following recommendation which hopefully compliments the result of our previous discussion around this subject:
> 
> You will likely find the APIs respond much fast if you apply sensible date boundaries to your operations when running the initial pull. As an example, you might choose to pull the data in 6 month blocks which gives the underlying database a much better chance of optimizing the query better as it will be able to use more indexes to filter the data internally
> 
> You strategy could be:
> 
> 1. Set Year (eg 2000)
> 2. Set Query data boundaries (either 1st Jan - 30th Jun or 1st Jul to 31st Dec)
> 3. Fetch appointments created in the boundaries set for that year (eg `GET https://platform.reapit.cloud/appointments/?fromArchive=False&includeCancelled=true&includeUnconfirmed=true&createdFrom=2000-01-01T00:00:00Z&createdTo=2000-07-01T00:00:00Z`)
> 4. Page through the results. Repeat step 2-4 for the second half of the year
> 5. Repeat entire process incrementing the year until you've read everything up to and including the current data
> 
> Again I appreciate this will be a refactor but you'll definitely get better performance. I've run some quick tests on the YOM database. You'll get better performance still if you fetch data a month at time, and so on.
> 
> Can you let me know your thoughts on the above, and how realistic implementing something like this will be?
> 
> Thanks

Hi @plittlewood-rpt,

Thanks for the suggestion, we are working on implementing this currently.

- Is there a known minimum `createdDate` value? 
Originally our full pull date is 1900-01-01, just to make sure we get all the data. However, with the above suggestions I imagine this would cause a lot of redundant requests. I'm aware Reapit hasn't been around forever, but was just wondering if there can be cases of archived data which could potentially have a created date pre 2000s for example.

Cheers,

Henry

**Comment by plittlewood-rpt** [comment]
Hi @BYM-Henry it all depends on the customer to be honest. I think the earliest date I've ever seen was about 1995. What you could do though, is run a single request GET /appointments?sortBy=created&pageSize=1&pageNumber=1 which will give you the earliest date

**Comment by plittlewood-rpt** [comment]
In addition though, I'd consider if you _really_ need all that data. I'm struggling to see what benefit having appointment data so old in your own system has any benefit

**Comment by alxbland** [comment]
Hi,
If I have understood this correctly then I would say that the appointment data will be used to trigger email campaigns based on a customers previous transaction with the business. 
I.e. Valuation appointment was more than 1 year ago and they didn't instruct etc...
Thanks, Alex

**Comment by plittlewood-rpt** [comment]
@alxbland  thanks - noted. I'd still question though what usefulness data > x years old has - it feels like there's a theshold that should be set somewhere (which would simplify what I'm suggesting above)

**Comment by alxbland** [comment]
Are we pulling everything or just 'subscribed' contacts - would that make a difference?

**Comment by BYM-Henry** [comment]
Hi,

Just to keep everyone updated we have just released a change on our side to allow us to pull data using the method recommended above.

We are currently running a full pull of data using it now.

Many Thanks,

Henry

**Comment by plittlewood-rpt** [comment]
That's great thanks Henry. Let me know how it goes

**Comment by plittlewood-rpt** [comment]
Hi @BYM-Henry I've just split this ticket up due to it containing two separate issues. I'll close this one since the appointments item is resolved.

**Comment by plittlewood-rpt** [comment]
Hi @BYM-Henry please can you let me know if you are still having problems with the areas API for YOM? I can't see that you've had any timeouts since 8th December and I can see you've made some successful requests this morning. I think the linked ticket can be closed but wanted to confirm with you first

**Comment by BYM-Henry** [comment]
Hi @plittlewood-rpt, sorry for the late response. But yeh we are still having issues with this. Our daily areas pulls for YOM work fine, but these generally comeback with empty responses. When trying to do a full pull of areas, will are still met with a 504 on certain created date ranges:

<img width="433" alt="image" src="https://github.com/reapit/foundations/assets/51915903/7ef3f2b3-f6aa-44a3-9624-8976057f80ae">
