### ISSUE TITLE
Real Time notification connected Error

### ISSUE THREAD

**Issue by MGill31** [reapit/foundations#11317]
**Describe the bug**
After logging into RPS, the notification "Real time notifications connection lost" and "Real time notifications connected" keeps popping up, indicating a connectivity issue. This is occurring on one of our staff member's account only. When I log in with my details, I don't experience this on their device. This also comes up when they log into other devices where others are not experiencing it either. However, I had noticed this come up once on my own device, but doesn't continue to appear after that.

**To Reproduce**
1. Login into RPS
2. Notifications keep popping up on Dashboard

**Expected behaviour**
Notification should not be appearing

**Screenshots** 
![image (4) (1)](https://github.com/user-attachments/assets/a637c01f-35d6-4eba-8bfa-6553f68d8695)
![second](https://github.com/user-attachments/assets/26d64db7-2f45-40a8-9001-8dac51c7b3ec)

**Comment by plittlewood-rpt** [comment]
Hi @MGill31 please can you provide some details about the company/user having the problem?

**Comment by MGill31** [comment]
Hi Team,

Can you please share your email address,so I can share my client and company details? 

Thank you

**Comment by plittlewood-rpt** [comment]
HI @MGill31 you can send the info to sinfo@reapitfoundations.zendesk.com
Thanks

**Comment by plittlewood-rpt** [comment]
Hi @MGill31 

If you restart AgencyCloud this should be resolved. Your system was upgraded to a version that enables some functionality that hasn't been rolled out in your region yet automatically. I've switched this off now.

Thanks
Pete

**Comment by MGill31** [comment]
Hi @plittlewood-rpt 
We restarted and reinstalled it on my end but we are still encountering the same problem.

Specifically, when logging into My client's RPS application, I am not receiving any pop-ups. Interestingly, when she logs in with her profile, the pop-ups keep coming on her profile. We tested this on different laptops, but the behavior remains consistent.

Thanks
