### ISSUE TITLE
CORS issue while using Sign In with Reapit Button and Properties API.

### ISSUE THREAD

**Issue by Emsysindiakt** [reapit/foundations#6695]
**Describe the bug**

We are working on a php solution and using JS based Sign in with Reapit Button integration to connect to Reapit. It was working fine before and we used to call required API calls to fetch the property data. In the last couple of days we are getting the following error

Access to fetch at 'https://platform.reapit.cloud/properties' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**To Reproduce**
This is the code we are using to execute 

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
<div id="reapit-connect-component"></div>
<script src="https://web-components.prod.paas.reapit.cloud/reapit-connect-component.js"></script>
<script>

  const connectHasSessionCallback = (reapitConnectBrowserSession) => {
    reapitConnectBrowserSession.connectSession().then(session => {
      console.log('Session is', session)
      console.log(session.loginIdentity.email, session.loginIdentity.developerId)
      fetch('https://platform.reapit.cloud/appointments', {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.accessToken}`,
          'api-version': '2020-01-31'
        }
      })
      .then(res => res.json())
      .then(appointments => console.log('Appointmemts are', appointments))

      fetch('https://platform.reapit.cloud/applicants', {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.accessToken}`,
          'api-version': '2020-01-31'
        }
      })
      .then(res => res.json())
      .then(applicants => console.log('applicants are', applicants))

      fetch('https://platform.reapit.cloud/properties', {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.accessToken}`,
          'api-version': '2020-01-31'
        }
      })
      .then(res => res.json())
      .then(properties => console.log('properties are', properties))

    })
  }

  ReapitConnectComponent && new ReapitConnectComponent({
    connectClientId: '28f4q8cqnr5712c2es7oh1ampu',
    connectUserPoolId: 'eu-west-2_eQ7dreNzJ',
    connectOAuthUrl: 'https://connect.reapit.cloud',
    connectLoginRedirectPath: '/reapit',
    connectLogoutRedirectPath: '/reapit/login',
    rootElement: '#reapit-connect-component',
    connectHasSessionCallback,
    companyName: 'My Company',
  })
</script>
  </body>
</html>

**Expected behaviour**
We would like to get the APIs to work and return the reponse 
https://platform.reapit.cloud/properties 

**Screenshots**
![image](https://user-images.githubusercontent.com/60339815/165272492-416021e6-2f5b-4b17-800a-9426fb006c09.png)

**Device (please complete the following information for web issues):**
Chrome

**Comment by plittlewood-rpt** [comment]
@Emsysindiakt this should now be resolved. Please can you check and confirm back to me. Thanks

**Comment by Emsysindiakt** [comment]
with the client id 28f4q8cqnr5712c2es7oh1ampu we are still getting the same CORS error

with the client id 2a945ernt4svoma4skmofod11a we are not getting CORS error but getting Server responded with a status of 400 error

**Comment by plittlewood-rpt** [comment]
@Emsysindiakt and are you hitting the API from the same location? (ie same server somewhere in the world)

**Comment by Emsysindiakt** [comment]
yes, same server and with same static IP.

One other developer is using the same account to test from different location with dynamic ip.

**Comment by Emsysindiakt** [comment]
It seems to be working now. Thank for fixing the issue.
