### ISSUE TITLE
Applicant record not updating

### ISSUE THREAD

**Issue by ebuildwebsolutions** [reapit/foundations#7774]
See ticket #7594 Adding ReasonId and SellingPostion to applicant record 

Using your sandbox environment the **PATCH** /applicants/{id} method for applicant records no longer updates.

I have created a test contact and applicant record in the sandbox using the POST /acontacts/ and  POST /applicants/. From this I got the Contact ID, Applicant ID and ETag variables.

I inserted these variables into the sandbox API function PATCH /applicants/{id} and the applicant record does not update.

When I call the /applicants/{id} the record has the same results.

Can you confirm why this is happening as I am getting the same results in live data.

Kind regards,

Philp.

**Specification**
- Project: Reapit.Services.Applicants
- Ensure that when selling position id is set that it doesn't get overwritten by the calls `SetPosition` in the Applicant class

**Comment by AshDeeming** [comment]
Hi @ebuildwebsolutions 
Could you advise the test contact ID so we can review please?

**Comment by plittlewood-rpt** [comment]
Hi @ebuildwebsolutions this should now be resolved

**Comment by ebuildwebsolutions** [comment]
Hi Pete,

That is still not updating in the sandbox or live environment.

Kind regards,

Philip.
________________________________

**Comment by plittlewood-rpt** [comment]
@ebuildwebsolutions please can you send me the actual request (curl or something)

**Comment by ebuildwebsolutions** [comment]
This was all done in the sandbox environment. I didn't write any code.


curl -X 'PATCH' \
  'https://platform.reapit.cloud/applicants/MKT220448' \
  -H 'accept: application/json' \
  -H 'If-Match: 17D70A2653247A0C98E0A32832E0AC2A' \
  -H 'Content-Type: application/json-patch+json' \
  -H 'api-version: 2020-01-31' \
  -H 'Authorization: Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzMmQ3NWYzNC02ODAxLTRiNWYtYjBmMy1hYzQyZjMzMmRmOTEiLCJjb2duaXRvOmdyb3VwcyI6WyJGb3VuZGF0aW9uc0RldmVsb3BlciJdLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0yLmFtYXpvbmF3cy5jb21cL2V1LXdlc3QtMl9lUTdkcmVOekoiLCJ2ZXJzaW9uIjoyLCJjbGllbnRfaWQiOiI0bDZqMHVucW9sNGswMmJzbDZxODlvZGVtNSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2xhbmRsb3Jkcy5yZWFkIGFnZW5jeUNsb3VkXC9vZmZpY2VzLndyaXRlIGFnZW5jeUNsb3VkXC9vZmZlcnMucmVhZCBhZ2VuY3lDbG91ZFwvcHJvcGVydGllcy53cml0ZSBhZ2VuY3lDbG91ZFwvYXBwbGljYW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvdGFza3MucmVhZCBhZ2VuY3lDbG91ZFwvaWRlbnRpdHljaGVja3MucmVhZCBhZ2VuY3lDbG91ZFwvcGF5bWVudHMucmVhZCBhZ2VuY3lDbG91ZFwvaWRlbnRpdHljaGVja3Mud3JpdGUgYWdlbmN5Q2xvdWRcL2tleXMucmVhZCBhZ2VuY3lDbG91ZFwvbGFuZGxvcmRzLndyaXRlIGFnZW5jeUNsb3VkXC9jb252ZXlhbmNpbmcud3JpdGUgYWdlbmN5Q2xvdWRcL2VucXVpcmllcy5yZWFkIGFnZW5jeUNsb3VkXC9zb3VyY2VzLndyaXRlIG9wZW5pZCBwcm9maWxlIGFnZW5jeUNsb3VkXC9wYXltZW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvbmVnb3RpYXRvcnMud3JpdGUgYWdlbmN5Q2xvdWRcL2FwcGxpY2FudHMucmVhZCBhZ2VuY3lDbG91ZFwvbmVnb3RpYXRvcnMucmVhZCBhZ2VuY3lDbG91ZFwvdmVuZG9ycy53cml0ZSBwaG9uZSBhZ2VuY3lDbG91ZFwvam91cm5hbGVudHJpZXMucmVhZCBhZ2VuY3lDbG91ZFwvY29tcGFuaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9wcm9wZXJ0aWVzLnJlYWQgYWdlbmN5Q2xvdWRcL3ZlbmRvcnMucmVhZCBhZ2VuY3lDbG91ZFwvY29udGFjdHMucmVhZCBhZ2VuY3lDbG91ZFwvZG9jdW1lbnRzLndyaXRlIGFnZW5jeUNsb3VkXC90YXNrcy53cml0ZSBhZ2VuY3lDbG91ZFwvdGVuYW5jaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9jb21wYW5pZXMucmVhZCBhZ2VuY3lDbG91ZFwvZW5xdWlyaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9jb252ZXlhbmNpbmcucmVhZCBhZ2VuY3lDbG91ZFwva2V5cy53cml0ZSBhZ2VuY3lDbG91ZFwvd29ya3NvcmRlcnMud3JpdGUgYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy5yZWFkIGFnZW5jeUNsb3VkXC9vZmZlcnMud3JpdGUgYWdlbmN5Q2xvdWRcL2pvdXJuYWxlbnRyaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9hcHBvaW50bWVudHMud3JpdGUgYWdlbmN5Q2xvdWRcL3RlbmFuY2llcy5yZWFkIGVtYWlsIGFnZW5jeUNsb3VkXC9hcmVhcy53cml0ZSBhZ2VuY3lDbG91ZFwvcmVmZXJyYWxzLndyaXRlIGFnZW5jeUNsb3VkXC9yZWZlcnJhbHMucmVhZCBhZ2VuY3lDbG91ZFwvY29udGFjdHMud3JpdGUgYWdlbmN5Q2xvdWRcL3dvcmtzb3JkZXJzLnJlYWQgYWdlbmN5Q2xvdWRcL29mZmljZXMucmVhZCBhZ2VuY3lDbG91ZFwvYXBwb2ludG1lbnRzLnJlYWQgYWdlbmN5Q2xvdWRcL3RyYW5zYWN0aW9ucy5yZWFkIiwiYXV0aF90aW1lIjoxNjY0Mjg1NTUyLCJleHAiOjE2NjQyODkxNTIsImlhdCI6MTY2NDI4NTU1MiwianRpIjoiYWM1YzgwZjEtMGM0OC00YzU2LWE3N2YtZjc0OGQyYmM2ZWVlIiwidXNlcm5hbWUiOiIzMmQ3NWYzNC02ODAxLTRiNWYtYjBmMy1hYzQyZjMzMmRmOTEifQ.H6UVTzXXlXLPQZzel2Pjam6q7Es9thQgfrlP2kyQJkpkfkTjWoXgIEIBKiIhngq4cKXMn4vvT1DchmMyHV_g4c1kDGONpmtTAUtKxxDCv3K_CQqQl4jBL-Aw-NrSMg6dzIfoj1IvZTKAOtmHELCqbTsXE00y34XQNvzLRderpsRvqe2kZcjnvN9O-mP8T436HJOQqMT0KiFqofCWFfpKD9ktSCppZiLkhxmzeRU8n-2_8coBiovKY8WlJjtcY_KcJ5H7_U_by9hQ-S6TpDrvXUXGOu4RdExtj3bZeA7Eww_Uo4eHRtuMB9BAATlSr6mgayYdWdJKXDGF5RzdLLvv0w' \
  -d '{
  "marketingMode": "buying",
  "currency": "GBP",
  "active": true,
  "notes": "this is a patch update test",
  "statusId": null,
  "sellingStatus": "completed",
  "sellingPosition": "sellingWithUs",
  "lastCall": "2019-11-12",
  "nextCall": "2022-12-29",
  "departmentId": "G",
  "solicitorId": "OXF18000012",
  "type": [
    "house",
    "maisonette",
    "cottage"
  ],
  "style": [
    "detached",
    "semiDetached"
  ],
  "situation": [
    "garden",
    "patio"
  ],
  "parking": [
    "garage"
  ],
  "age": [
    "period"
  ],
  "locality": [
    "rural"
  ],
  "bedroomsMin": 4,
  "bedroomsMax": 5,
  "receptionsMin": 1,
  "receptionsMax": 2,
  "bathroomsMin": 1,
  "bathroomsMax": null,
  "parkingSpacesMin": null,
  "parkingSpacesMax": null,
  "locationType": "areas",
  "locationOptions": [
    "SOL",
    "BHM",
    "WLV"
  ],
  "buying": {
    "reasonId": null,
    "positionId": null,
    "priceFrom": 250000,
    "priceTo": 275000,
    "decoration": null
  },
  "renting": null,
  "externalArea": {
    "type": "acres",
    "amountFrom": 2,
    "amountTo": 3
  },
  "internalArea": {
    "type": "squareFeet",
    "amount": 1500
  },
  "source": {
    "id": "RMV",
    "type": "source"
  },
  "officeIds": [
    "OXF",
    "SOL"
  ],
  "negotiatorIds": [
    "JAS"
  ],
  "metadata": {
    "CustomField1": "CustomValue1",
    "CustomField2": true
  }
}'

________________________________

**Comment by ebuildwebsolutions** [comment]
Okay When I call the applicant ID MKT220448 the data is the old data.

This should so show the updated record?


curl -X 'GET' \
  'https://platform.reapit.cloud/applicants/MKT220448' \
  -H 'accept: application/json' \
  -H 'api-version: 2020-01-31' \
  -H 'Authorization: Bearer eyJraWQiOiJFXC9TcnVuTzVCR0xBMk1yT3phY2RjWFkwVVdqRVB1cVB5N3hIb1FWbnJGdz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzMmQ3NWYzNC02ODAxLTRiNWYtYjBmMy1hYzQyZjMzMmRmOTEiLCJjb2duaXRvOmdyb3VwcyI6WyJGb3VuZGF0aW9uc0RldmVsb3BlciJdLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0yLmFtYXpvbmF3cy5jb21cL2V1LXdlc3QtMl9lUTdkcmVOekoiLCJ2ZXJzaW9uIjoyLCJjbGllbnRfaWQiOiI0bDZqMHVucW9sNGswMmJzbDZxODlvZGVtNSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYWdlbmN5Q2xvdWRcL2xhbmRsb3Jkcy5yZWFkIGFnZW5jeUNsb3VkXC9vZmZpY2VzLndyaXRlIGFnZW5jeUNsb3VkXC9vZmZlcnMucmVhZCBhZ2VuY3lDbG91ZFwvcHJvcGVydGllcy53cml0ZSBhZ2VuY3lDbG91ZFwvYXBwbGljYW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvdGFza3MucmVhZCBhZ2VuY3lDbG91ZFwvaWRlbnRpdHljaGVja3MucmVhZCBhZ2VuY3lDbG91ZFwvcGF5bWVudHMucmVhZCBhZ2VuY3lDbG91ZFwvaWRlbnRpdHljaGVja3Mud3JpdGUgYWdlbmN5Q2xvdWRcL2tleXMucmVhZCBhZ2VuY3lDbG91ZFwvbGFuZGxvcmRzLndyaXRlIGFnZW5jeUNsb3VkXC9jb252ZXlhbmNpbmcud3JpdGUgYWdlbmN5Q2xvdWRcL2VucXVpcmllcy5yZWFkIGFnZW5jeUNsb3VkXC9zb3VyY2VzLndyaXRlIG9wZW5pZCBwcm9maWxlIGFnZW5jeUNsb3VkXC9wYXltZW50cy53cml0ZSBhZ2VuY3lDbG91ZFwvbmVnb3RpYXRvcnMud3JpdGUgYWdlbmN5Q2xvdWRcL2FwcGxpY2FudHMucmVhZCBhZ2VuY3lDbG91ZFwvbmVnb3RpYXRvcnMucmVhZCBhZ2VuY3lDbG91ZFwvdmVuZG9ycy53cml0ZSBwaG9uZSBhZ2VuY3lDbG91ZFwvam91cm5hbGVudHJpZXMucmVhZCBhZ2VuY3lDbG91ZFwvY29tcGFuaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9wcm9wZXJ0aWVzLnJlYWQgYWdlbmN5Q2xvdWRcL3ZlbmRvcnMucmVhZCBhZ2VuY3lDbG91ZFwvY29udGFjdHMucmVhZCBhZ2VuY3lDbG91ZFwvZG9jdW1lbnRzLndyaXRlIGFnZW5jeUNsb3VkXC90YXNrcy53cml0ZSBhZ2VuY3lDbG91ZFwvdGVuYW5jaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9jb21wYW5pZXMucmVhZCBhZ2VuY3lDbG91ZFwvZW5xdWlyaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9jb252ZXlhbmNpbmcucmVhZCBhZ2VuY3lDbG91ZFwva2V5cy53cml0ZSBhZ2VuY3lDbG91ZFwvd29ya3NvcmRlcnMud3JpdGUgYWdlbmN5Q2xvdWRcL2RvY3VtZW50cy5yZWFkIGFnZW5jeUNsb3VkXC9vZmZlcnMud3JpdGUgYWdlbmN5Q2xvdWRcL2pvdXJuYWxlbnRyaWVzLndyaXRlIGFnZW5jeUNsb3VkXC9hcHBvaW50bWVudHMud3JpdGUgYWdlbmN5Q2xvdWRcL3RlbmFuY2llcy5yZWFkIGVtYWlsIGFnZW5jeUNsb3VkXC9hcmVhcy53cml0ZSBhZ2VuY3lDbG91ZFwvcmVmZXJyYWxzLndyaXRlIGFnZW5jeUNsb3VkXC9yZWZlcnJhbHMucmVhZCBhZ2VuY3lDbG91ZFwvY29udGFjdHMud3JpdGUgYWdlbmN5Q2xvdWRcL3dvcmtzb3JkZXJzLnJlYWQgYWdlbmN5Q2xvdWRcL29mZmljZXMucmVhZCBhZ2VuY3lDbG91ZFwvYXBwb2ludG1lbnRzLnJlYWQgYWdlbmN5Q2xvdWRcL3RyYW5zYWN0aW9ucy5yZWFkIiwiYXV0aF90aW1lIjoxNjY0Mjg1NTUyLCJleHAiOjE2NjQyODkxNTIsImlhdCI6MTY2NDI4NTU1MiwianRpIjoiYWM1YzgwZjEtMGM0OC00YzU2LWE3N2YtZjc0OGQyYmM2ZWVlIiwidXNlcm5hbWUiOiIzMmQ3NWYzNC02ODAxLTRiNWYtYjBmMy1hYzQyZjMzMmRmOTEifQ.H6UVTzXXlXLPQZzel2Pjam6q7Es9thQgfrlP2kyQJkpkfkTjWoXgIEIBKiIhngq4cKXMn4vvT1DchmMyHV_g4c1kDGONpmtTAUtKxxDCv3K_CQqQl4jBL-Aw-NrSMg6dzIfoj1IvZTKAOtmHELCqbTsXE00y34XQNvzLRderpsRvqe2kZcjnvN9O-mP8T436HJOQqMT0KiFqofCWFfpKD9ktSCppZiLkhxmzeRU8n-2_8coBiovKY8WlJjtcY_KcJ5H7_U_by9hQ-S6TpDrvXUXGOu4RdExtj3bZeA7Eww_Uo4eHRtuMB9BAATlSr6mgayYdWdJKXDGF5RzdLLvv0w'



{
  "id": "MKT220448",
  "created": "2022-09-27T13:39:58Z",
  "modified": "2022-09-27T13:39:58Z",
  "marketingMode": "buying",
  "currency": "GBP",
  "active": true,
  "notes": "Looking to move his mother back into the area",
  "sellingStatus": "exchanged",
  "sellingPosition": "renting",
  "statusId": "GE",
  "lastCall": "2019-11-12",
  "nextCall": "2022-12-29",
  "departmentId": "G",
  "solicitorId": "OXF18000012",
  "type": [
    "house",
    "maisonette",
    "cottage"
  ],
  "style": [
    "detached",
    "semiDetached"
  ],
  "situation": [
    "garden",
    "patio"
  ],
  "parking": [
    "garage"
  ],
  "age": [
    "period"
  ],
  "locality": [
    "rural"
  ],
  "specialFeatures": [],
  "unmappedRequirements": [],
  "bedroomsMin": 4,
  "bedroomsMax": 5,
  "receptionsMin": 1,
  "receptionsMax": 2,
  "bathroomsMin": 1,
  "bathroomsMax": 0,
  "parkingSpacesMin": 0,
  "parkingSpacesMax": 0,
  "locationType": "areas",
  "locationOptions": [
    "SOL",
    "BHM",
    "WLV"
  ],
  "archivedOn": null,
  "fromArchive": false,
  "buying": {
    "priceFrom": 250000,
    "priceTo": 275000,
    "decoration": [],
    "reasonId": null,
    "positionId": null
  },
  "renting": null,
  "externalArea": {
    "type": "acres",
    "amountFrom": 2,
    "amountTo": 3
  },
  "internalArea": {
    "type": "squareFeet",
    "amount": 1500
  },
  "source": {
    "id": "RMV",
    "type": "source"
  },
  "commercial": null,
  "regional": null,
  "officeIds": [
    "OXF",
    "SOL"
  ],
  "negotiatorIds": [
    "JAS"
  ],
  "related": [
    {
      "id": "MKT22001869",
      "name": "Mr George Smith",
      "title": "Mr",
      "forename": "George",
      "surname": "Smith",
      "dateOfBirth": null,
      "type": "contact",
      "homePhone": null,
      "workPhone": null,
      "mobilePhone": "07737565543",
      "email": ***@***.***",
      "fromArchive": false,
      "primaryAddress": {
        "buildingName": "",
        "buildingNumber": "",
        "line1": "",
        "line2": "",
        "line3": "",
        "line4": "",
        "postcode": "",
        "countryId": "GB"
      }
    }
  ],
  "_eTag": "\"17D70A2653247A0C98E0A32832E0AC2A\"",
  "_links": {
    "self": {
      "href": "/applicants/MKT220448"
    },
    "documents": {
      "href": "/documents/?associatedType=applicant&associatedId=MKT220448"
    },
    "offers": {
      "href": "/offers/?applicantId=MKT220448"
    },
    "appointments": {
      "href": "/appointments/?attendeeType=applicant&attendeeId=MKT220448"
    },
    "department": {
      "href": "/departments/G"
    },
    "solicitor": {
      "href": "/companies/OXF18000012"
    },
    "status": {
      "href": "/configuration/applicantStatuses/GE"
    },
    "offices": {
      "href": "/offices/?id=OXF&id=SOL"
    },
    "negotiators": {
      "href": "/negotiators/?id=JAS"
    },
    "relationships": {
      "href": "/applicants/MKT220448/relationships"
    },
    "areas": {
      "href": "/areas/?id=SOL&id=BHM&id=WLV"
    },
    "source": {
      "href": "/sources/RMV"
    }
  },
  "_embedded": null,
  "metadata": {
    "CustomField1": "CustomValue1",
    "CustomField2": true
  }
}

________________________________

**Comment by plittlewood-rpt** [comment]
Hmm that's interesting thanks - I've just recorded a video of the actions you are taking. Can you review and confirm if they are exactly the same steps? It could be your browser serving old data as it's behaving absolutely fine here. 


https://user-images.githubusercontent.com/30798627/192548747-7a546e87-2b59-4aa6-873b-4e5fa5437094.mp4

**Comment by ebuildwebsolutions** [comment]
Hi Pete,

I have disabled the cache and I can see the notes field has updated.


"notes": "These notes have been updated",

I will test on the live environment.

Kind regards,

Philip.
________________________________

**Comment by plittlewood-rpt** [comment]
Hi @ebuildwebsolutions I'm struggling with this one as everything seems fine here - would you be able to do a screencast of what you're seeing? I'll keep having a dig around to see if I can find any logs to suggest what might be going on

**Comment by ebuildwebsolutions** [comment]
Hi Pete,

Found the issue. When I entered in the eTag it was not in inverted commas. I have adjusted and I can now can see the data update on the sandbox site.

Kind regards,

Philip.
________________________________

**Comment by plittlewood-rpt** [comment]
Thanks - the eTag needs to be wrapped in quotation marks (see https://foundations-documentation.reapit.cloud/api/api-documentation#optimistic-concurrency). It looks like the error isn't being surfaced correcvtly when they are not supplied. I'll get something logged separate for dealing with that

**Comment by plittlewood-rpt** [comment]
#7795 logged to deal with underlying issue

**Comment by ebuildwebsolutions** [comment]
Hi Pete,

Here is a recording of my screen. Hopefully this will help.

https://ebuildwebsolutions.ie/video/reapit-patch-fail.mp4

Kind regards,

Philip.
________________________________

**Comment by plittlewood-rpt** [comment]
Hi @ebuildwebsolutions - your link does not work for me unfortunately. I thought we had sorted this issue out? If there's a new issue please can I ask that you open a new issue. Thanks

**Comment by ebuildwebsolutions** [comment]
Hi Pete,

I am not sure how this ticket got updated as I sent that email when you sent me your video. This ticket can be closed as it has been resolved.

Kind regards,

Philip.
