### ISSUE TITLE
Error connecting to DIARY_A table in the Data Warehouse

### ISSUE THREAD

**Issue by LyndsayCremin** [reapit/foundations#8025]
Hi There, 

I am encountering an error when attempting to connect to the DIARY_A table in the data warehouse - please see image below. I am connecting via Power BI using the snowflake connector. 

This is the only table with this error, I can connect to all other tables without issue. This did happen previously, as if I recall correctly the schema had to be re-provisioned. 

Can I trouble you to investigate the same please?

Many thanks, 

Lyndsay

![Error Message](https://user-images.githubusercontent.com/90459251/198585477-fe18cbfa-eacb-4353-9e56-8ded9cf416b8.PNG)

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin sorry for the delay in responding to your query. Can you confirm whether or not you have reprovisioned the share yet?

**Comment by LyndsayCremin** [comment]
Hi @plittlewood-rpt , no problem. No, I haven't done anything since I logged the call. Is there something I need to do on our end?

**Comment by plittlewood-rpt** [comment]
hi @LyndsayCremin I think this should be resolved by reprovisioning the share. You can do this in the [Data Warehouse App ](https://data-warehouse-app.reapit.cloud/) - can you do this and let me know if it resolves the problem? If so I'll look into what the underlying cause may be

**Comment by LyndsayCremin** [comment]
Thanks Pete, apologies I have never done that before. Do I just simply hit 'Refresh Share' as seen in the attached screenshot?
![Snip](https://user-images.githubusercontent.com/90459251/203595080-a3e2bec1-674d-405d-b0f9-be9bc31b0241.PNG)

**Comment by LyndsayCremin** [comment]
Thanks Pete, I have done that and unfortunately I'm still getting the same error.

**Comment by plittlewood-rpt** [comment]
Thanks - I'll keep looking and see if I can understand what's going wrong here

**Comment by LyndsayCremin** [comment]
Hi @plittlewood-rpt, I just wanted to check in to see if there was any update available on this? I am also encountering the same issue with the IDCHECK table.

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin still working on this I'm afraid. I'm a bit closer but still not quite there yet.

**Comment by plittlewood-rpt** [comment]
Hi @LyndsayCremin so I think we've been able to unpick what's happened here. For the operational schema (raw AgencyCloud data) we used to share this data to customers using database views, instead of sharing the tables directly. This is the setup you've got that was provisioned back in September last year. In October we had to make some changes to adjust how this provisioning was done and now we give read access to the tables themselves (there's some technical reasons behind this). The main issue we have now is that when I correct this for you you are going to need to update your connection string. You may lose access to your data for a short period so I don't want to just go ahead and do this without planning it in with you as I know you use the warehouse quite heavily

**Comment by LyndsayCremin** [comment]
Hi @plittlewood-rpt , can you make the change today please and then I can work on updating it from our side. I presume the server details are the same I will just need to point it to the new table?

**Comment by plittlewood-rpt** [comment]
Thanks for coming back to me. The server is the same yes, it's the database and schema name that will change

**Comment by LyndsayCremin** [comment]
Thanks @plittlewood-rpt, before you make the change could I trouble you to send me on the new details please? Will the username and password we use stay the same?

**Comment by plittlewood-rpt** [comment]
Yep no problem. I'll get your email address from our system and send them over. The new tables are already there actually so you can start using them right away the access just might stop working temporarily whilst I get the data marketplace app back in sync

**Comment by plittlewood-rpt** [comment]
I've just sent you an email with the details

**Comment by LyndsayCremin** [comment]
Thanks Pete, got the email. That's perfect.

**Comment by plittlewood-rpt** [comment]
Issue is now resolved
