### ISSUE TITLE
Bug/Duplicate records within the PROPERTY_INSTRUCTION_CHECKS view 

### ISSUE THREAD

**Issue by eddloughran** [reapit/foundations#9781]
**Is your feature request related to a problem? Please describe.**
There are duplicate records of the same check within the PROPERTY_INSTRUCTION_CHECKS, these have all the same information other than a different ID, as I understand there should only be one record per check per property. 

**Describe the solution you'd like**
A non changing primary key within the view

**Describe alternatives you've considered**
Using a combination of the property ID and and the property check as a primary key - this doesn't work because of the duplicate records of the same check for the same property

**Additional context**

**Specification**
- Project: Analytics Schema
- This is happening because if pre instruction checks are not changed from the configured list, they are never stored in the database. They are only persisted at the point a change is made to one of the pre configured items OR a custom check is added. The analytics schema generates the pseudo checks using a different id mechanism to the one that comes into play at the point the checks are saved (and get their own unique key). This is thepoint at which the check id in the analytics schema dataset will change. To get around this we should
  - For pseudo checks AND any checks with a srcCode, use PROPERTYCODE_CHECKSRCCODE to generate the id. This will never change when a pseudo check gets committed to the db, resolving the reported issue
  - For checks without a srcCode, use the tenchk.code to generate the id as these will only ever exist when explicitly stored in the db
  - The same problem likely exists in the TENANCY_CHECKS view model data, so check this at the same time

**Comment by plittlewood-rpt** [comment]
Hi @eddloughran can I just check which customer you are working on behalf of so I can make sure I'm looking at the correct data? Thanks

**Comment by plittlewood-rpt** [comment]
@eddloughran this should now be resolved. Any issues please let me know. Thanks

**Comment by eddloughran** [comment]
Hi @plittlewood-rpt,

We've currently got 2 clients using the data warehouse.
I'm still experiencing the same issue, am I correct in thinking that a record in the PROPERTY_INSTRUCTION_CHECKS table should be unique based on the columns: PROPERTY_ID, CHECK_NAME, CREATED_DATE? 
I'm seeing a number of records that have duplicates of these with different IDs but every other column the same

**Comment by plittlewood-rpt** [comment]
Hi there. Please can you let me know which customers you are having issues with, and provide some examples of data you're struggling with?

**Comment by eddloughran** [comment]
The _CUSTOMER_ID is ANE and an example of the duplicates is 
RPOPERTY_CODE = a5127f5123b77f6e59bbec711ccc6128
CHECK_NAME = General & viewing notes updated
CREATED_DATE = 2023-04-29

**Comment by plittlewood-rpt** [comment]
Thanks - I'll have a look at this today

**Comment by plittlewood-rpt** [comment]
Hi @eddloughran these checks are actually duplicated in the customer's data (see below). It would potentially be the wrong thing to do for us to de-duplicate these as part of analytics schema generation, as particular for lettings operations you can have multiple instruction checks with the same name. For example, when the property is first marketed, it would have one set of checks. If a tenant then ends a tenancy say 12 months later and it goes back on the market, you'd have a second set of instruction checks. At this point, the first set would appear as archived in the analytics schema. This could easily be repeated multiple times if it's a property that the agent has looked after for a number of years 

![image](https://github.com/reapit/foundations/assets/30798627/6ed7f6cb-8b55-4b5f-aba9-944210604eda)

**Comment by eddloughran** [comment]
Hi @plittlewood-rpt  thanks for getting back to me. It makes sense that a property would have multiple checks against it if it were to come back on to the market, however I would have through that the dates of these checks would not be the same. If a property  is on the market (e.g. in 2020) and has checks done then, when it comes back in the market (e.g. in 2023) should the checks not have different created dates against them (2020 and 2023 respectfully)?

**Comment by plittlewood-rpt** [comment]
Hi @eddloughran I've spent a good chunk of time looking at this customer's data today and it does look like it's accurate based on what is in their database and how their configuration is set up. They have a number of properties where the data has physically been duplicated, which could perhaps be as a result of a bug or a data conversion issue - I've had a quick look at some of the examples and it could also be due to two different negotiators having the same property record open and making changes to the instruction checks at the same time. To complicate matters, they also have checks with the same name setup for both sales and lettings marketing modes. As a result, properties that are dual marketed (for example property YTS200220 which has analytics property id 78d9a3f719a94a705c8576af614d6617 will appear as though it has duplicate checks, when really one is for sales and the other for lettings. 

You can view a summary of the affected data by running the following query:

```
with data as (
    SELECT
        COUNT(*) AS num,
        property_id,
        check_name 
    FROM property_instruction_checks 
    WHERE check_name != '' 
    GROUP BY property_id, check_name 
    HAVING num > 1 ORDER BY num DESC 
)

SELECT
    SUM(num) AS totalChecks,
    LISTAGG(check_name, ', ') AS checks,
    property_id, 
    properties.code
FROM data
LEFT JOIN properties ON data.property_id = properties.id 
GROUP BY property_id, code ORDER BY totalChecks DESC
```

The duplicate check between sales and lettings is the one called "Material information added" which I think might be a misconfiguration.

I think therefore there's some different things that need to happen, all of which I need to pass this over to another team to look at

1) I can get a ticket logged with our service desk to look at cleaning up the duplicate rows, which only apply to a small handful of properties so this should be fairly easy to manage. 
2) I can get a ticket logged to look at why there is a duplicate check across sales and lettings modes as this should really be covered by a single check. I could add a mode field to the property_instruction_checks view model but I still worry this might be confusing for people looking at that data.
3) I can log a ticket for our service team to investigate if there is a bug here in the CRM where we are missing some validation before committing the checks to the database

Are you a third party working for this customer or do you have access to the CRM yourself - it just determines how I need to log these items. 

Thanks

**Comment by plittlewood-rpt** [comment]
Internal tickets logged:
